spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/movie_award_db?useSSL=false'
    username: db_user
    password: P@$$w0rd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
